export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as Landing } from './Landing/Landing'
export { default as About } from './About/About'
export { default as Musica } from './Musica/Musica'
export { default as Fiesta } from './Fiesta/Fiesta'
export { default as Blog } from './Blog/Blog'
export { default as SingleBlog } from './Blog/SingleBlog/SingleBlog'
export { default as Education } from './Education/Education'
export { default as Experience } from'./Experience/Experience'
export { default as Contacts } from'./Contacts/Contacts'
export { default as DressCode } from'./DressCode/DressCode'
export { default as Projects } from'./Asistencia/Asistencia'

export { default as BackToTop } from'./BackToTop/BackToTop'